# These are supported funding model platforms

github: die
patreon: # fly
open_collective: bye
ko_fi: why
tidelift: cry
community_bridge: lie
liberapay: shy
issuehunt: dry
otechie: dye
custom: die in a hole
