# These are supported funding model platforms

github: get a life m8.
patreon: get out of my house!
open_collective: suck my ****!!
ko_fi: what is this bro?
tidelift: who are you???
community_bridge: society must burn :)
liberapay: get a life kid
issuehunt: 0.001(minecraft) > 100000(fortnite + fortnite: chapter 2)
otechie: there is no programming only stack overflow
custom: thanks for the support, now die in a hole 
